
// CPU Cycles per second (4 MHZ clock).
const int CYCLES_PER_SECOND = 4194304;

const int CYCLES_PER_FRAME = CYCLES_PER_SECOND / 60;


// Audio Sample Rate.
const int SAMPLE_RATE = 44000;

const int CYCLES_PER_SAMPLE = CYCLES_PER_SECOND / SAMPLE_RATE;

const int CYCLES_PER_SOUND_TIMER_TICK = CYCLES_PER_SECOND / 256;

const int VOICE_MAX_VOLUME = 32767 / 4;

const int CYCLES_PER_ENVELOPE_TICK = CYCLES_PER_SECOND / 64;

const int CYCLES_PER_PERIOD_SWEEP_TICK = CYCLES_PER_SECOND / 128;

const int ROM_BANK_0_START = 0x0000;
const int ROM_BANK_0_END = 0x3FFF;

const int ROM_BANK_1_START = 0x4000;
const int ROM_BANK_1_END = 0x7FFF;

const int VIDEO_RAM_START = 0x8000;
const int VIDEO_RAM_END = 0x9FFF;

const int EXTERNAL_RAM_START = 0xA000;
const int EXTERNAL_RAM_END = 0xBFFF;

const int WORK_RAM_START = 0xC000;
const int WORK_RAM_END = 0xDFFF;

const int ECHO_RAM_START = 0xE000;
const int ECHO_RAM_END = 0xFDFF;

const int OAM_RAM_START = 0xFE00;
const int OAM_RAM_END = 0xFE9F;

const int FORBIDDEN_RAM_START = 0xFEA0;
const int FORBIDDEN_RAM_END = 0xFEFF;

const int IO_RAM_START = 0xFF00;
const int IO_RAM_END = 0xFF7F;

const int HIGH_RAM_START = 0xFF80;
const int HIGH_RAM_END = 0xFFFE;

const int INTERRUPT_ENABLE_REGISTER = 0xFFFF;

const int RAM_RTC_ENABLE_REGISTER_START = 0x0000;
const int RAM_RTC_ENABLE_REGISTER_END = 0x1FFF;

const int ROM_BANK_SELECT_REGISTER_START = 0x2000;
const int ROM_BANK_SELECT_REGISTER_END = 0x3FFF;

const int RAM_BANK_RTC_SELECT_REGISTER_START = 0x4000;
const int RAM_BANK_RTC_SELECT_REGISTER_END = 0x5FFF;

const int LATCH_RTC_REGISTER_START = 0x6000;
const int LATCH_RTC_REGISTER_END = 0x7FFF;
